AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFormation template to create an S3 bucket
Resources:
  RahulS3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rahul-s3-bucket-1234567890
      Tags:
        - Key: Name
          Value: RahulS3Bucket
        - Key: Environment
          Value: Production

  RahulEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0953476d60561c955  # Example AMI ID, replace with a valid one for your region
      KeyName: mykey # Replace with your key pair name
      Tags:
        - Key: Name
          Value: RahulEc2Instance
        - Key: Environment
          Value: Production
